lememe/urls.py
from django.conf.urls import url
from lememe import views

app_name = "lememe"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^search/$', views.search, name='search'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    # url(r'^add_category/$', views.add_category, name='add_category'),
    # url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^post/(?P<post_id>[\w]+)/add_preference/$', views.ajax_add_preference, name='add_preference'),
    url(r'^post/(?P<post_id>[\w]+)/add_comment/$', views.ajax_create_comment, name='add_comment'),
    url(r'^post/(?P<post_id>[\w]+)$', views.show_post, name='show_post'),
    url(r'^user/settings/$', views.show_settings, name='show_settings'),
    url(r'^user/(?P<username>[\w\-]+)/$', views.show_profile, name='show_profile'),
    url(r'^feeling_lucky/$', views.feeling_lucky, name='feeling_lucky'),
    # url(r'^restricted/', views.restricted, name='restricted'),
]

lememe_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from lememe import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^lememe/', include('lememe.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lememe/forms.py
from django import forms
from django.contrib.auth.models import User
from lememe.models import UserProfile, Post, Comment, Preference, Category
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            'text': forms.Textarea(attrs={
                'id': 'comment-text',
                'required': True,
                'placeholder': 'Enter a comment...',
                'rows': 1,
                'cols': 69
            }),
        }


class PostForm(forms.ModelForm):
    # title = forms.CharField(max_length=128, help_text="Please enter the title of the post.")
    # category = forms.ModelChoiceField(queryset=Category.objects.all(),help_text="Category")
    # image = forms.FileInput()
    # views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Post
        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        # exclude = ["category",]
        exclude = ('client_id', 'id', 'date', 'user', 'views')
        # exclude = []
        # fields = (
        #     'title',
        #     'category',
        #     'image',
        # )
        # or specify the fields to include (i.e. not include the category field)
        # fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username',
                  'password',
                  'first_name',
                  'last_name',
                  'email',
                  )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('bio', 'website', 'picture')


# Update settings form
class UpdateUserSettingsForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
        ]


# Update settings form
class UpdateUserProfileSettingsForm(UserChangeForm):
    password = None
    picture = forms.ImageField(label='Profile Picture', required=False,
                               error_messages={'invalid': "Image files only"}, widget=forms.FileInput)

    class Meta:
        model = UserProfile
        fields = [
            'picture',
            'website',
            'bio',
        ]

        
class PasswordChangeCustomForm(PasswordChangeForm):
    error_css_class = 'has-error'
    error_messages = {'password_incorrect':
                          "Your old password is incorrect. Try again."
                      }
    old_password = forms.CharField(required=True, label='Old Password',
                                   widget=forms.PasswordInput(attrs={
                                       'class': 'form-control'},
                                       render_value=True),
                                   error_messages={
                                       'required': 'Old password field cannot be blank'})

    new_password1 = forms.CharField(required=True, label='New Password',
                                    widget=forms.PasswordInput(attrs={
                                        'class': 'form-control'},
                                        render_value=True),
                                    error_messages={
                                        'required': 'New password field cannot be blank'})
    new_password2 = forms.CharField(required=True, label='Confirm New Password',
                                    widget=forms.PasswordInput(attrs={
                                        'class': 'form-control'},
                                        render_value=True),
                                    error_messages={
                                        'required': 'New password field cannot be blank'})

    def clean(self):
        cd = self.cleaned_data
        if cd.get('new_password1') != cd.get('new_password2'):
            self.add_error('new_password2', "passwords do not match !")
            raise forms.ValidationError('password mismatch')
        return cd

    def clean_new_password2(self):
        password2 = self.cleaned_data.get("new_password2", "")
        if not password2:  # If both passwords has value
            raise forms.ValidationError(_(u"Passwords can't be blank."))
        return password2

lememe/views.py
from datetime import datetime
import random, json
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required # login_required redirects to index if user is not logged in (see settings.py->)
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.contrib.staticfiles.templatetags.staticfiles import static


# Import the models
from lememe.models import UserProfile, Post, Comment, Preference, Category
# Import the forms
from lememe.forms import UserForm, UserProfileForm, PostForm, CommentForm,\
    UpdateUserSettingsForm, UpdateUserProfileSettingsForm, PasswordChangeCustomForm

def index(request):
    context_dict = {}
    if request.method == "GET":
        keyword = request.GET.get("keyword",None)
        if keyword:
            context_dict["keyword"] = keyword

        # Popular posts paging
        popular_posts = Post.objects.all().order_by("-views")
        popular_page = request.GET.get('popular_page', 1)

        popular_paginator = Paginator(popular_posts, 2)
        try:
            popular_posts = popular_paginator.page(popular_page)
        except PageNotAnInteger:
            popular_posts = popular_paginator.page(1)
        except EmptyPage:
            popular_posts = popular_paginator.page(popular_paginator.num_pages)

        context_dict["popular_posts"] = popular_posts

        # New posts paging
        new_posts = Post.objects.all().order_by("-date")
        new_page = request.GET.get('new_page', 1)

        if request.GET.get('new_page') != None:
            context_dict["activate_new_tab"] = True
        else:
            context_dict["activate_new_tab"] = False

        new_paginator = Paginator(new_posts, 2)
        try:
            new_posts = new_paginator.page(new_page)
        except PageNotAnInteger:
            new_posts = new_paginator.page(1)
        except EmptyPage:
            new_posts = new_paginator.page(new_paginator.num_pages)

        context_dict["new_posts"] = new_posts

    # Call the helper function to handle the cookies
    # visitor_cookie_handler(request)

    # context_dict['visits'] = request.session.get('visits')

    # Obtain the Response object early so we can add cookie information.
    # this statement can also be before handling cookies in the case of client side cookies
    response = render(request, 'lememe/index.html', context=context_dict)

    # Return response back to user, updating any cookies that need changed.
    return response


@login_required
def comment(request,post):
    # create a form instance and populate it with data from the request:
    form = CommentForm(request.POST)

    # check whether it's valid:
    if form.is_valid():
        # process the data in form.cleaned_data as required
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
        # redirect to a new URL:
        # return HttpResponseRedirect(reverse('lememe:show_post', args=[request.post.id]))
    else:
        form = CommentForm()

@csrf_exempt
def ajax_create_comment(request,post_id):
    print("in ajax view")
    # try:
    post = Post.objects.get(client_id=post_id)
    # except Post.DoesNotExist:
    #     post = None

    print("got the post")
    if request.method == 'POST' and post is not None:
        comment_text = request.POST.get('comment_text')
        response_data = {}

        comment = Comment.objects.create(text=comment_text, user=request.user, post=post)
        comment.save()

        response_data['result'] = 'Create post successful!'
        response_data['commentpk'] = comment.pk
        response_data['text'] = comment.text
        response_data['created'] = comment.date.strftime('%b. %d, %Y, %I:%M %p')
        response_data['user'] = comment.user.username
        response_data['number_of_comments'] = int(Comment.objects.filter(post=post).count())
        response_data['post'] = post.client_id

        print("got here")
        try:
            # if user doesn't have a profile picture send the default pic url
            user_profile = UserProfile.objects.get(user=comment.user)
            response_data['user_pic_url'] = user_profile.picture.url
        except UserProfile.DoesNotExist:
            response_data['user_pic_url'] = static('images/placeholder_profile.png')


        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


@csrf_exempt
def ajax_add_preference(request,post_id):

    try:
        post = Post.objects.get(client_id=post_id)
    except Post.DoesNotExist:
        return None

    if request.method == 'POST' and post is not None:
        preference = request.POST.get('preference')
        print(preference)

        if preference == "true":
            preference = True
        else:
            preference = False

        response_data = {}

        # Check if a preference already exists in the database
        try:
            old_preference = Preference.objects.get(user=request.user, post=post)
        except Preference.DoesNotExist:
            old_preference = None

        # If the user post preference exists, update the liked attribute
        if old_preference:
            old_preference.liked = preference
            old_preference.save()
        else:
            # If it does not exist, create it
            new_preference = Preference.objects.create(user=request.user, post=post, liked=preference)
            new_preference.save()

        # Likes Ratio
        response_data['like_ratio'] = post.get_rating()
        # What user's preference is
        response_data['preference'] = preference

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


def show_post(request, post_id):
    context_dict = {}

    try:
        # Check if a post with the given client id exists
        post = Post.objects.get(client_id=post_id)

        # increment the post's view count
        # post.views += 1
        # post.save()
        post.increament_view_count()

        # if this is a POST request we need to process the form data
        if request.method == 'POST':
            comment(request, post)

        comments = Comment.objects.filter(post=post).order_by('-date')
        context_dict['post'] = post
        context_dict['comments'] = comments
        context_dict['comment_form'] = CommentForm()

        return render(request, 'lememe/post.html', context_dict)

    except Post.DoesNotExist:
        # If the requested post does not exist redirect to homepage
        return HttpResponseRedirect(reverse('lememe:index'))






def show_category(request, category_name_slug):

    context_dict = {}

    if request.method == "GET":

        try:
            # Can we find a category name slug with the given name?
            # If we can't, the .get() method raises a DoesNotExist exception.
            # So the .get() method returns one model instance or raises an exception.
            category = Category.objects.get(slug=category_name_slug)


            # Popular posts paging
            # Filter by Category
            popular_posts = Post.objects.filter(category=category).order_by("-views")
            popular_page = request.GET.get('popular_page', 1)

            popular_paginator = Paginator(popular_posts, 2)
            try:
                popular_posts = popular_paginator.page(popular_page)
            except PageNotAnInteger:
                popular_posts = popular_paginator.page(1)
            except EmptyPage:
                popular_posts = popular_paginator.page(popular_paginator.num_pages)

            context_dict["popular_posts"] = popular_posts

            # New posts paging
            # Filter by Category
            new_posts = Post.objects.filter(category=category).order_by("-date")
            new_page = request.GET.get('new_page', 1)

            if request.GET.get('new_page') != None:
                context_dict["activate_new_tab"] = True
            else:
                context_dict["activate_new_tab"] = False

            new_paginator = Paginator(new_posts, 2)
            try:
                new_posts = new_paginator.page(new_page)
            except PageNotAnInteger:
                new_posts = new_paginator.page(1)
            except EmptyPage:
                new_posts = new_paginator.page(new_paginator.num_pages)

            context_dict["new_posts"] = new_posts
            context_dict['active_cat'] = category

        except Category.DoesNotExist:
            # if Category does not exist, return None in context dictionary
            return HttpResponseRedirect(reverse('lememe:index'))

    # Go render the response and return it to the client.
    return render(request, 'lememe/category.html', context=context_dict)


def about(request):

    return render(request, 'lememe/about.html', {})

def contact(request):
    return render(request, 'lememe/contact.html', {})


def show_profile(request, username):
    context_dict = {}
    # In case no user with this username exists
    try:
        user = User.objects.get(username=username)
        profile = UserProfile.objects.get(user=user)
        posts = Post.objects.filter(user=user)
        liked_posts = Preference.objects.filter(user=user)

templates/lememe/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load lememe_template_tags %}

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Pieris Kimonos, Callum Firth, Iacovos Kelepeniotis and Rishi Vinod">

    <title id="title_elem">
        {% block title_block %}
        Lememe
        {% endblock %}
    </title>

    <!--load page icon-->
    <link rel="icon" href="{% static 'images\lememe_icon.jpg' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

</head>
<body class="radial-gradient">
<div>
    {% block welcome_block %}
    {% endblock %}
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    {% url 'lememe:index' as url %}
    <a class="navbar-brand" href="{% url 'lememe:index' %}">
        <img id="lememe_logo" class="{% if request.path == url %} breath-animation duration{% endif %}" src="{% static 'images\lememe_logo.svg' %}">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mx-auto nav-fill">

            {% url 'lememe:index' as url %}
            <li class="nav-item{% if request.path == url %} active{% endif %}">
                <a class="nav-link" href="{{ url }}">Home {% if request.path == url %}
                    <span class="sr-only">(current)</span>{% endif %}</a>
            </li>

            {% url 'lememe:show_post' post_id=post.client_id  as url %}
            <li class="nav-item{% if request.path == url %} active{% endif %}">
                <a class="nav-link" style="overflow: auto; white-space: nowrap;"
                   href="{% url 'lememe:feeling_lucky' %}">Feeling Lucky? {% if request.path == url %}
                    <span class="sr-only">(current)</span>{% endif %}</a>
            </li>

            {% url 'lememe:contact' as url %}
            <li class="nav-item{% if request.path == url %} active{% endif %}">
                <a class="nav-link" href="{{ url }}" style="overflow: auto; white-space: nowrap;">Contact Us {% if request.path == url %}
                    <span class="sr-only">(current)</span>{% endif %}</a>
            </li>

            {% url 'lememe:about' as url %}
            <li class="nav-item{% if request.path == url %} active{% endif %}">
                <a class="nav-link" href="{{ url }}">About {% if request.path == url %}
                    <span class="sr-only">(current)</span>{% endif %}</a>
            </li>

            <li class="divider-vertical d-none d-lg-block"></li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    {% url 'lememe:index' as index_url %}
                    {% url 'lememe:show_profile' user.username as profile_url %}
                    {% url 'lememe:upload' as upload %}
                    {% url 'lememe:show_settings' as settings %}
                    {% with profile_url|add:","|add:upload|add:","|add:settings as user_pages %}

                    <a class="nav-link dropdown-toggle{% if request.path in user_pages and request.path != index_url %} active{% endif %}" href=""
                       id="dropdown01"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% endwith %}
                        {{ user.username.capitalize }}
                        <div class="photo" style="margin-left: 10px"><img src="{{ MEDIA_URL }}{{ user.user_profile.picture }}?v={% random_number 4 %}"
                                onerror="this.src='{% static 'images/placeholder_profile.png' %}'"></div>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'lememe:show_profile' user.username %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'lememe:upload' %}">Upload</a>
                        <a class="dropdown-item" href="{% url 'lememe:show_settings' %}">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'lememe:logout' %}">Logout</a>
                    </div>
            </li>
            {% else %}
                {% url 'lememe:login' as url %}
            <li class="nav-item{% if request.path == url %} active{% endif %}">

                <a class="nav-link" href="{{ url }}">Login</a>
            </li>
                {% url 'lememe:register' as url %}
            <li class="nav-item{% if request.path == url %} active{% endif %}">
                <a class="nav-link" href="{{ url }}">Register</a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline justify-content-center justify-content-lg-end" action="{% url 'lememe:search' %}" method="GET">
            <input id="search_text_input" class="form-control mr-sm-2 w-50" name="keyword" type="text" value="{{ keyword }}"
                   required="required"
                   placeholder="Search"
                   aria-label="Search">
            <button id="search_button" class="btn btn-secondary my-2 my-sm-0 bg-warning text-dark" type="submit"><img
                    src="{% static 'icons/search.svg'%}"></button>
        </form>
    </div>
</nav>
{% block body_block %}
<main role="main" class="container">
    <div class="main_body">
        <div class="shadow-lg p-3 mb-5 bg-white rounded">
        {% block main_block %}


            <!-- col means column, md >=992px (Also use xs, sm and lg), and the 3 represents the size of the column
            3 * 4 = 12 (A 6 column layout would use 2 if they had equal size) -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    {% block sidebar_block %}
                    {% get_category_list active_cat %}
                    {% endblock %}
                </div>
                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12">
                    {% block rightbody_block %}
                    {% endblock %}
                </div>
            </div>
        {% endblock %}
        </div>
    </div>
    <br>
    {% endblock %}

<div id="BacktoTop" class="bg-dark">
    <h6>Back To </h6>
    <h6 class="badge badge-primary d-block">Top!</h6>
</div>

</main><!-- /.container -->
<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script>window.jQuery || document.write('<script src="static/js/jquery-3.3.1.slim.min.js"><\/script>')</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/customscripts.js' %}"></script>
</body>
</html>

templates/lememe/post.html
{% extends 'lememe/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block rightbody_block %}
    <div class="container">
        <h1 class="text-left font-weight-bolder">{{ post.title }}</h1>
        <h2 class="text-left font-weight-lighter">{{ post.category }}</h2><br>

        <div class="card border-0 shadow">
            <img src="{{ MEDIA_URL }}{{ post.image }}" class="card-img-top" alt="Post's Image">

            <div class="card-body container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="media">
                            <a href="{% url 'lememe:show_profile' post.user.username %}">
                                <img class="d-flex mr-3 image-cropper" style="width:80px;height:80px;margin-left:25px"
                                     src="{{ MEDIA_URL }}{{ post.user }}/{{ post.user }}_profile_pic.jpg"
                                     onerror="this.src='{% static 'images/placeholder_profile.png' %}'"
                                     alt="Generic placeholder image">
                            </a>

                        </div>
						<div class="media-body">
                                <div class="mt-0">
                                    <a href="{% url 'lememe:show_profile' post.user.username %}">{{ post.user.username.capitalize }}</a>
                                </div>
                            </div>
                    </div>
                    <div class="col-sm-5 ">
                        {{ post.date }}
                    </div>
                    <div class="col-sm-4">
                        <div id="post_like_bar_parent" class="progress{% if post.get_total_preferences != 0 %} bg-danger{% endif %}">
                            <div id="post_like_bar" class="progress-bar bg-success" role="progressbar" style="width: {{ post.get_rating }}%" aria-valuenow="41"
                                 aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    {% if user.is_authenticated %}
                        <div class="row mt-2 pl-3 pr-3 btn-group-sm" role="group">
                            <button id="option1" type="submit" class="btn btn-labeled btn-success col"
                                    data-action="{% url 'lememe:show_post' post_id=post.client_id %}">
                                <div class="badge post-label">
                                    <img src="{% static 'icons/thumbsup.svg' %}">
                                </div>
                            </button>
                            <button id="option2" type="submit" class="btn btn-labeled btn-danger col">
                                <div class="badge post-label">
                                    <img src="{% static 'icons/thumbsdown.svg' %}">
                                </div>
                            </button>
                        </div>
                    {% else %}
                        <span id="disabled_comment_btn" data-toggle="popover"
                          data-content="Please <a href='{% url 'lememe:login' %}'>login</a> in order to like or dislike." title="Action not allowed" data-html="true">
                        <div class="row mt-2 pl-3 pr-3 btn-group-sm" role="group">
                            <button id="option1" type="submit" class="btn btn-labeled btn-success col disabled"
                                    data-action="{% url 'lememe:show_post' post_id=post.client_id %}">
                                <div class="badge post-label">
                                    <img src="{% static 'icons/thumbsup.svg' %}">
                                </div>
                            </button>
                            <button id="option2" type="submit" class="btn btn-labeled btn-danger col disabled">
                                <div class="badge post-label">
                                    <img src="{% static 'icons/thumbsdown.svg' %}">
                                </div>
                            </button>
                        </div>
                        </span>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <br>
        <h4 class="text-left">Comments (<span id="number_of_comments">{{ comments|length }}</span>)</h4>
        {% if user.is_authenticated %}
            {% if comment_form %}
                <form id="comment_form" action="{% url 'lememe:show_post' post_id=post.client_id %}"
                      method="post">

                    {% csrf_token %}
                    <div class="input-group">
                        <div class="fieldWrapper" id="the_comment">
                            {% render_field comment_form.text class="form-control" aria-label="" aria-describedby="basic-addon1" %}
                        </div>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit" value="Comment">Submit</button>
                        </div>
                    </div>

                </form>

            {% endif %}
        {% else %}
            <form id="comment_form" class="container" action="" disabled>
                <div class="input-group">
                    <div class="fieldWrapper" id="the_comment">
                        {% render_field comment_form.text class="form-control" %}
                    </div>
                    <span id="disabled_comment_btn" class="d-inline-block input-group-append" data-toggle="popover"
                          data-content="Please <a href='{% url 'lememe:login' %}'>login</a> in order to comment." title="Action not allowed" data-html="true">
                        <button class="btn btn-primary" style="pointer-events: none;" type="button" disabled>Submit</button>
                    </span>
                </div>

            </form>
        {% endif %}
        <br>
        <div id="all_comments">
            {% for comment in comments %}
                <div class="card">
                    <div class="card-body">
                        <div class="media">
                            <a href="{% url 'lememe:show_profile' comment.user.username %}">
                                <img class="d-flex mr-3 image-cropper"
                                     src="{{ MEDIA_URL }}{{ comment.user }}/{{ comment.user }}_profile_pic.jpg"
                                     onerror="this.src='{% static 'images/placeholder_profile.png' %}'"
                                     alt="Generic placeholder image">
                            </a>
                            <div class="media-body">
                                <div class="mt-0 text-left">
                                    <a href="{% url 'lememe:show_profile' comment.user.username %}">{{ comment.user.username.capitalize }}</a> -

                                    <span class="card-subtitle mb-2 text-muted">{{ comment.date|date:'M. d, Y, f A' }}</span>
                                </div>
                                <p class="card-text text-left">
                                    {{ comment.text }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/lememe/sidebar_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>